# Generated by Django 5.0.4 on 2024-05-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(max_length=400)),
                ('category', models.CharField(choices=[('Social Networking', 'social networking'), ('Entertainment', 'entertainment'), ('Utilities', 'utilities'), ('Productivity', 'productivity'), ('Health and Fitness', 'health and fitness'), ('Finance', 'finance'), ('Shopping', 'shopping'), ('News', 'news'), ('Lifestyle', 'lifestyle')], max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField()),
                ('logo', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('ifLogged', models.BooleanField(default=False)),
                ('token', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
    ]
