# Generated by Django 2.2.18 on 2024-05-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20240503_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(max_length=400)),
                ('category', models.CharField(choices=[('Social Networking', 'social networking'), ('Entertainment', 'entertainment'), ('Utilities', 'utilities'), ('Productivity', 'productivity'), ('Health and Fitness', 'health and fitness'), ('Finance', 'finance'), ('Shopping', 'shopping'), ('News', 'news'), ('Lifestyle', 'lifestyle')], max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('points', models.IntegerField()),
                ('logo', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
