# Generated by Django 2.2.18 on 2024-05-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('social networking', 'Social Networking'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('productivity', 'Productivity'), ('health and fitness', 'Health and Fitness'), ('finance', 'Finance'), ('shopping', 'Shopping'), ('news', 'News'), ('lifestyle', 'Lifestyle')], max_length=100),
        ),
    ]
