# Generated by Django 2.2.18 on 2024-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_auto_20240504_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(related_name='users', to='Authentication.Task'),
        ),
    ]
